version: '3'

services:
  queueserver:
    image: rabbitmq:3.8-management
    restart: unless-stopped
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  Sales:
    image: cquirosj/quickstart-sales:1
    build:
      context: .
      dockerfile: Sales/Dockerfile
    
  webserver:
    image: nginx
    ports:
      - "80:80"